name: Bug report
description: Create a report to help us improve AWSF
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I try to...
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Search for '...'
        3. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Windows (WSL)
        - Other
    validations:
      required: true
      
  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: "3.9.7"
    validations:
      required: true
      
  - type: input
    id: fzf-version
    attributes:
      label: fzf Version
      description: Output of `fzf --version`
      placeholder: "0.35.0"
      
  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant error output
      render: shell
